import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { SettingsProvider } from "./context/settings";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    return (
        <html lang="en">
            <body className={poppins.variable}>
                <SettingsProvider>
                    <div className="flex min-h-screen w-full flex-col items-center bg-chart-1">
                        {children}
                    </div>
                </SettingsProvider>
            </body>
        </html>
    );
}
